# This workflow runs the tests for the given codebase

name: CI - Unit Tests

on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code Repository
      uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Set up node 
      uses: actions/setup-node@v1
      with:
        node_version: '12.x'
      
    - name: Install packages and create build
      run: |
        node -v
        npm install
        npm run test

  build:
    runs-on: ubuntu-latest
    needs: [ test ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code Repository
      uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Set up node 
      uses: actions/setup-node@v1
      with:
        node_version: '12.x'
      
    - name: Install packages and create build
      run: |
        node -v
        npm install
        npm run build

    - name: Deploy Build
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
