name: Build & Deploy

on:
  push:
    tags: 'v*.*.*'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v2

    - name: Set up node 
      uses: actions/setup-node@v1
      with:
        node_version: '12.x'
      
    - name: Install packages and create build
      run: |
        node -v
        npm install
        npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v2

    - name: Set up node 
      uses: actions/setup-node@v1
      with:
        node_version: '12.x'
      
    - name: Prepare Build
      run: |
        node -v
        npm install
        npm run build

    - name: Deploy Build
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
